<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>size_256GB</name>
   <tag></tag>
   <elementGuidId>141376ac-0edf-4679-a40b-bdef4f17ea35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.attr-item.active > span.attr-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-view']/div/div[3]/section/section/div/div[2]/div[2]/section/ul/li[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;256GB&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c324539-2ee6-49ec-85c6-4c1d25232d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attr-item-text</value>
      <webElementGuid>39e3deed-b47b-4984-8932-421f774bdee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      256GB
                    </value>
      <webElementGuid>576079fe-a318-4ef7-aedd-e7f06880b3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;page-view__child&quot;]/section[@class=&quot;page-pdp page-pdp&quot;]/section[@class=&quot;page-pdp_content&quot;]/div[@class=&quot;page-pdp_content__main&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;product-attr&quot;]/section[@class=&quot;product-attr_item&quot;]/ul[1]/li[@class=&quot;attr-item active&quot;]/span[@class=&quot;attr-item-text&quot;]</value>
      <webElementGuid>171357f0-8976-4958-abb4-392ba0c7e480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div[3]/section/section/div/div[2]/div[2]/section/ul/li[3]/span</value>
      <webElementGuid>961ac0cf-9408-43a4-b682-4fdc7526c2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::span[3]</value>
      <webElementGuid>27a78688-1f18-4aa7-b88a-2d7671a05ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm hiểu thêm'])[2]/following::span[4]</value>
      <webElementGuid>93cb0e35-08f2-4709-a33b-2bffd69750dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/preceding::span[1]</value>
      <webElementGuid>c3949846-7aed-462a-bb49-6dc99ae0e5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dark green'])[1]/preceding::span[1]</value>
      <webElementGuid>7e308917-30ce-4bbd-b09d-db4f664e0a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='256GB']/parent::*</value>
      <webElementGuid>e7a65196-0896-47cd-b8c9-cf22b066cd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>d2d86651-5471-4bd9-8939-9b79a83e469a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                      256GB
                    ' or . = '
                      256GB
                    ')]</value>
      <webElementGuid>f8e3ee07-db64-435f-8244-c6ed1801bc8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
