<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submenu_Discover</name>
   <tag></tag>
   <elementGuidId>a51e78f2-169c-432c-82b2-8b8e31c76320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>submenu_Demo_info</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
